### ISSUE TITLE
Studying the run2 UBDT efficiency

### ISSUE THREAD

**Issue by emilyj816** [umd-lhcb/pidcalib2#1]
Hi Yipeng,

I just have a few quick questions. 
1) I was able to generate the efficiency plots for P, and I was wondering whether "P" or "Brunel_P" would be the right variable to use in this case. I assume "P", since we are looking at Turbo (https://twiki.cern.ch/twiki/bin/view/LHCb/PIDCalibPackage), but can you confirm if this is correct?

2) I wasn't able to find the variable PT, setting `--bin-var PT` gives the error
```
[E 220616 11:48:51 binning:181] No 'PT' binning defined for particle Mu_nopt
```
I assume there's a different naming convention, and I was wondering where to find a list of the variables that can be used for binning?

3. I'd like to open up the histograms to check and make sure nothing went wrong, the script produces a pickle file. I read [here](https://gitlab.cern.ch/lhcb-rta/pidcalib2) that you can use the command `pidcalib2.pklhisto2root` to convert the pickle file to root, but I get this error:
```
Traceback (most recent call last):
  File "/home/ejiang/pidcalib2/.virtualenv/bin/pidcalib2.pklhisto2root", line 5, in <module>
    from pidcalib2.pklhisto2root import main
  File "/home/ejiang/pidcalib2/.virtualenv/lib/python3.9/site-packages/pidcalib2/pklhisto2root.py", line 26, in <module>
    import ROOT
ModuleNotFoundError: No module named 'ROOT'
```
I'm not having any trouble accessing ROOT from this directory though, is there anything I can do to fix this? Or should I be using alternative methods to open the histogram?

Thank you in advance for the help!

**Comment by yipengsun** [comment]
First, you probably want to use the offline-reconstructed variables, like `Brunel_P`, `Brunel_PT`.

Second, that error makes sense, because that `pklhisto2root` script requires ROOT in the nix shell, which I haven't been listing. Probably I need to list `root` as a dependency.

**Comment by emilyj816** [comment]
Hi @yipengsun ,
I get the error `No 'Brunel_PT' binning defined for particle Mu_nopt`. Can you think of anything that might be going wrong here?

**Comment by yipengsun** [comment]
Hmm, I guess there's no default binning defined for `PT`: https://github.com/umd-lhcb/pidcalib2/blob/master/src/pidcalib2/binning.py

If the program refused to continue, maybe you can define the `Brunel_PT` binning in that file, re-enter the nix shell with either `nix develop` or `direnv reload`, and try again.

**Comment by yipengsun** [comment]
For now consider this done.
