### ISSUE TITLE
Make pidcalib2 load friends

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/pidcalib2#3]
Currently each time we update UBDT, we need to merge the friend ntuples to the main one, which is a huge pain (2.7 TB to merge).

We need to extend `pidcalib2` to be able to read stuff from friends.

**Comment by yipengsun** [comment]
It looks like the `pidcalib2` uses this to open a root file:

https://github.com/umd-lhcb/pidcalib2/blob/935f69cfd71f878245adaa22a257a16d9eb596dc/src/pidcalib2/pid_data.py#L230-L232

**Comment by ZishuoYang** [comment]
Uproot developer's answers regarding friend-like operation: 

https://stackoverflow.com/questions/60390875/reading-ttree-friend-with-uproot

https://github.com/scikit-hep/uproot3/issues/314

**Comment by yipengsun** [comment]
Also something like this: https://stackoverflow.com/questions/47655296/pandas-merge-two-datasets-with-same-number-of-rows

**Comment by yipengsun** [comment]
@emilyj816 It looks like now the friend works. Can you try pull the `master`, merge it into your branch, run `nix develop` again, and try regenerating the efficiency plots?

BTW the P samples are still not ready. I've restarted the UBDT friend generation for those but it's gonna take awhile.

**Comment by emilyj816** [comment]
Hi Yipeng, I've regenerated the efficiency plots and they look the same as the ones from earlier today--I assume this means your code is working correctly.

**Comment by yipengsun** [comment]
Hmm, this is weird, because supposedly you are now using Greg's re-trained UBDT, which has a pre-cut.

**Comment by yipengsun** [comment]
Can you push your latest change to github (basically, I'd like to check that you've merged the `master` branch)?

**Comment by emilyj816** [comment]
Hi @yipengsun, I've just created a new branch called `efficiency_study` with my local branch on it. Tried pulling from `master`, running `direnv reload`, and re-generating the plots, still have the same as before.

**Comment by yipengsun** [comment]
I see. Indeed that branch contains the latest friend changes. Does this mean that Greg's re-train has no noticeable improvements?

You should report this to Phoebe and see what she thinks.

Perhaps I should just re-generate the friends one more time to make sure I'm using the correct XML file. But I'm 99% sure that I already did.

**Comment by yipengsun** [comment]
Also, you changed the default `Mu` binning. Can you explain why?

I guess this won't make the `Pi` curve any better. Still, if you extend `Mu` binning very far away from the default one, you may get some weird behaviors (like negative efficiencies).

**Comment by emilyj816** [comment]
Hi @yipengsun , `P` binning should be the same for all species, but I changed the default `Mu` binning for `PT` since the bins in the low `PT` region looked strange (i.e. negative efficiencies, jumping around), presumably due to not enough events in this area? So I made a large bin containing a lot of the low `PT` bins. Could you also remind me what the new precut on the re-trained UBDT is as well?

**Comment by yipengsun** [comment]
I see. For the pre-cut, I think it's a loose Muon cut (like `PIDmu > 2`) but you should ask Phoebe to get the definite answer.

**Comment by ZishuoYang** [comment]
@emilyj816 for comparing with previous plots, I think it makes sense to keep the same pre-cuts. It would also be useful to have updated efficiency plots in P/PT bins.

**Comment by yipengsun** [comment]
This functionality is implemented. Closed.
